# Generated by Django 4.2.5 on 2023-09-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Editor", "Editor"),
                    ("Viewer", "Viewer"),
                ],
                default="Viewer",
                max_length=10,
            ),
        ),
    ]
