# Generated by Django 4.2.5 on 2023-09-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=300)),
                ("Googledata", models.JSONField(blank=True, null=True)),
                ("Redditdata", models.JSONField(blank=True, null=True)),
                ("Ytdata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "topic_data",
            },
        ),
    ]
